import { setRequestLocale } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { createSupabaseServiceRoleClient } from '@/lib/supabase/service-role';
import { verifyToken } from '@/lib/security/signed-tokens';
import { ReviewFormClient } from './review-form-client';

export const dynamic = 'force-dynamic';

/**
 * Phase 63b — Public review submission.
 *
 * The customer reaches this page via a signed token in the
 * post-appointment email (V1: link generated by admin via the
 * appointment detail drawer; auto-send after completion = V1.5).
 *
 * The token names a specific appointment; we verify the signature,
 * resolve the appointment + barber for context, and render a star
 * rating form. Submission goes through `submitPublicReview` which
 * re-verifies the token server-side (defense in depth — never trust
 * the client-side validation).
 */
export default async function ReviewPage(props: {
  params: Promise<{ locale: string; token: string }>;
  // Plan 043 (step 1) — `?rating=N` from the email's one-tap star links.
  // The page is already force-dynamic, so reading it costs no caching.
  searchParams: Promise<{ rating?: string }>;
}) {
  const params = await props.params;
  const searchParams = await props.searchParams;

  const { locale, token } = params;

  setRequestLocale(locale);

  // Clamp to a valid star count; anything else (absent, garbage, 0, 9)
  // falls back to 0 = nothing pre-selected. The form still requires an
  // explicit Submit — the deep-link only seeds the selection.
  const parsedRating = Number.parseInt(searchParams.rating ?? '', 10);
  const initialRating = Number.isInteger(parsedRating) && parsedRating >= 1 && parsedRating <= 5
    ? parsedRating
    : 0;

  const payload = verifyToken(decodeURIComponent(token), 'review');
  if (!payload) {
    // 404 on bad / expired token. We deliberately don't distinguish
    // between "no such appointment" and "token expired" — leaking that
    // would help someone enumerate valid appointment IDs.
    notFound();
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const supabase = createSupabaseServiceRoleClient() as any;
  const apptRes = await supabase
    .from('appointments')
    .select('id, shop_id, barber_id, client_id, start_at, public_link_version')
    .eq('id', payload.resourceId)
    .limit(1);
  const appt = ((apptRes.data as Array<{
    id: string;
    shop_id: string;
    barber_id: string;
    client_id: string;
    start_at: string;
    public_link_version: number | null;
  }> | null) ?? [])[0];
  if (!appt) notFound();
  // Revocation (plan 013): stale token version → 404, same as a bad/expired
  // token. Absent ⇒ 0 keeps legacy links valid until the first revoke.
  if ((payload.ver ?? 0) !== (appt.public_link_version ?? 0)) notFound();

  // Pull the shop + barber names so the form can address the customer
  // by context ("How was your visit with Olivier?"). Both reads bypass
  // RLS via the service-role client — the token IS the auth here.
  const [shopRes, barberRes] = await Promise.all([
    // Plan 043 (step 4) — `public_review_url` widened in so the thank-you can
    // hand a happy reviewer to the shop's Google listing.
    supabase.from('shops').select('name, public_review_url').eq('id', appt.shop_id).limit(1),
    supabase.from('barbers').select('display_name').eq('id', appt.barber_id).limit(1),
  ]);
  const shopRow =
    ((shopRes.data as Array<{ name: string; public_review_url: string | null }> | null) ?? [])[0] ??
    null;
  const shopName = shopRow?.name ?? '?';
  const publicReviewUrl = shopRow?.public_review_url ?? null;
  const barberName =
    ((barberRes.data as Array<{ display_name: string }> | null) ?? [])[0]?.display_name ?? null;

  // Check if a review already exists for this appointment — duplicate
  // submissions are blocked at the server-action layer, but rendering
  // a "thanks, already received" message here is friendlier than
  // letting them fill out the form and bounce.
  const existingRes = await supabase
    .from('reviews')
    // Plan 043 (step 2) — `rating` widened in so a returning visitor's
    // thank-you echoes the rating they ACTUALLY gave, not a generic 5★.
    .select('id, status, rating')
    .eq('appointment_id', appt.id)
    .limit(1);
  const existing = ((existingRes.data as Array<{
    id: string;
    status: string;
    rating: number | null;
  }> | null) ?? [])[0];

  return (
    <ReviewFormClient
      locale={locale}
      token={token}
      shopName={shopName}
      barberName={barberName}
      alreadySubmitted={Boolean(existing)}
      submittedRating={existing?.rating ?? null}
      initialRating={initialRating}
      publicReviewUrl={publicReviewUrl}
    />
  );
}
