import { setRequestLocale } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { createSupabaseServiceRoleClient } from '@/lib/supabase/service-role';
import { verifyToken } from '@/lib/security/signed-tokens';
import { ReviewFormClient } from './review-form-client';

export const dynamic = 'force-dynamic';

/**
 * Phase 63b — Public review submission.
 *
 * The customer reaches this page via a signed token in the
 * post-appointment email (V1: link generated by admin via the
 * appointment detail drawer; auto-send after completion = V1.5).
 *
 * The token names a specific appointment; we verify the signature,
 * resolve the appointment + barber for context, and render a star
 * rating form. Submission goes through `submitPublicReview` which
 * re-verifies the token server-side (defense in depth — never trust
 * the client-side validation).
 */
export default async function ReviewPage({
  params: { locale, token },
}: {
  params: { locale: string; token: string };
}) {
  setRequestLocale(locale);

  const payload = verifyToken(decodeURIComponent(token), 'review');
  if (!payload) {
    // 404 on bad / expired token. We deliberately don't distinguish
    // between "no such appointment" and "token expired" — leaking that
    // would help someone enumerate valid appointment IDs.
    notFound();
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const supabase = createSupabaseServiceRoleClient() as any;
  const apptRes = await supabase
    .from('appointments')
    .select('id, shop_id, barber_id, client_id, start_at')
    .eq('id', payload.resourceId)
    .limit(1);
  const appt = ((apptRes.data as Array<{
    id: string;
    shop_id: string;
    barber_id: string;
    client_id: string;
    start_at: string;
  }> | null) ?? [])[0];
  if (!appt) notFound();

  // Pull the shop + barber names so the form can address the customer
  // by context ("How was your visit with Olivier?"). Both reads bypass
  // RLS via the service-role client — the token IS the auth here.
  const [shopRes, barberRes] = await Promise.all([
    supabase.from('shops').select('name').eq('id', appt.shop_id).limit(1),
    supabase.from('barbers').select('display_name').eq('id', appt.barber_id).limit(1),
  ]);
  const shopName = ((shopRes.data as Array<{ name: string }> | null) ?? [])[0]?.name ?? '?';
  const barberName =
    ((barberRes.data as Array<{ display_name: string }> | null) ?? [])[0]?.display_name ?? null;

  // Check if a review already exists for this appointment — duplicate
  // submissions are blocked at the server-action layer, but rendering
  // a "thanks, already received" message here is friendlier than
  // letting them fill out the form and bounce.
  const existingRes = await supabase
    .from('reviews')
    .select('id, status')
    .eq('appointment_id', appt.id)
    .limit(1);
  const existing = ((existingRes.data as Array<{ id: string; status: string }> | null) ?? [])[0];

  return (
    <ReviewFormClient
      locale={locale}
      token={token}
      shopName={shopName}
      barberName={barberName}
      alreadySubmitted={Boolean(existing)}
    />
  );
}
